spring.application.name=backend
#spring.docker.compose.enabled=false
spring.jpa.hibernate.ddl-auto=update
logging.level.root=INFO
logging.level.com.hairhub.backend=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level [%logger{36}] - %msg%n
logging.file.name=logs/hairhub.log